# Generated by Django 4.1.4 on 2023-04-18 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('book', models.SmallIntegerField(db_index=True)),
                ('chapter', models.SmallIntegerField(db_index=True)),
                ('verse', models.SmallIntegerField()),
                ('text', models.CharField(blank=True, max_length=30, null=True)),
                ('trailer', models.CharField(blank=True, max_length=5, null=True)),
                ('speech', models.CharField(blank=True, max_length=10, null=True)),
                ('person', models.CharField(blank=True, max_length=10, null=True)),
                ('gender', models.CharField(blank=True, max_length=10, null=True)),
                ('number', models.CharField(blank=True, max_length=10, null=True)),
                ('verb_tense', models.CharField(blank=True, max_length=10, null=True)),
                ('verb_stem', models.CharField(blank=True, max_length=10, null=True)),
                ('suffix_person', models.CharField(blank=True, max_length=10, null=True)),
                ('suffix_gender', models.CharField(blank=True, max_length=10, null=True)),
                ('suffix_number', models.CharField(blank=True, max_length=10, null=True)),
                ('gloss', models.CharField(blank=True, max_length=30, null=True)),
                ('lex_frequency', models.IntegerField()),
                ('occ_frequency', models.IntegerField()),
                ('penalty', models.DecimalField(decimal_places=4, max_digits=7)),
                ('lex_id', models.IntegerField(db_index=True)),
            ],
        ),
    ]
