# Generated by Django 4.1.4 on 2024-01-12 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0004_passage_tags"),
    ]

    operations = [
        migrations.CreateModel(
            name="Algorithm",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("verbs", models.JSONField(default=list)),
                ("frequencies", models.JSONField(default=list)),
                ("construct_nouns", models.JSONField(default=list)),
                ("clauses", models.JSONField(default=list)),
                ("qere_penalty", models.FloatField(default=7)),
                ("penalize_by_stem", models.BooleanField(default=True)),
                ("taper_discount", models.FloatField(default=1)),
                ("proper_noun_divisor", models.FloatField(default=2)),
                ("skip_stops", models.BooleanField(default=True)),
                (
                    "divided_by",
                    models.CharField(
                        choices=[("option1", "Option 1"), ("option2", "Option 2")],
                        max_length=50,
                    ),
                ),
            ],
        ),
    ]
