# Generated by Django 4.1.4 on 2024-05-28 01:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0007_algorithm_phrases_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="algorithm",
            name="proper_noun_divisor",
            field=models.FloatField(
                default=2,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="qere_penalty",
            field=models.FloatField(
                default=7,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="taper_discount",
            field=models.FloatField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(10),
                ],
            ),
        ),
    ]
