# Generated by Django 4.1.4 on 2024-05-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0008_alter_algorithm_proper_noun_divisor_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="word",
            name="gloss",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="ketiv",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="lex",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="qere",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="text",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
