# databases:
#   - name: mysitedb
#     plan: free
#     databaseName: mysite
#     user: mysite

services:
  - type: web
    plan: free
    name: mysite
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn gradedhebrew.asgi:application -k uvicorn.workers.UvicornWorker"