# Generated by Django 4.1.4 on 2023-06-07 21:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_word_ketiv_word_language_word_lex_word_lex_set_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="passage",
            name="tags",
            field=models.TextField(blank=True, null=True),
        ),
    ]
