# Generated by Django 4.1.4 on 2023-04-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Passage",
            fields=[
                ("id", models.IntegerField(primary_key=True, serialize=False)),
                ("start_word", models.IntegerField(blank=True, null=True)),
                ("end_word", models.IntegerField(blank=True, null=True)),
                (
                    "book",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "start_chapter",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "end_chapter",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "start_verse",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("end_verse", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "word_count",
                    models.PositiveSmallIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "penalty",
                    models.DecimalField(db_index=True, decimal_places=4, max_digits=7),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="word",
            name="book",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="chapter",
            field=models.PositiveSmallIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name="word",
            name="verse",
            field=models.PositiveSmallIntegerField(),
        ),
    ]
