# Generated by Django 4.1.4 on 2024-01-12 23:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0005_algorithm"),
    ]

    operations = [
        migrations.RenameField(
            model_name="algorithm",
            old_name="penalize_by_stem",
            new_name="penalize_by_verb_stem",
        ),
        migrations.RemoveField(
            model_name="algorithm",
            name="divided_by",
        ),
        migrations.RemoveField(
            model_name="algorithm",
            name="skip_stops",
        ),
        migrations.AddField(
            model_name="algorithm",
            name="include_stop_words",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="algorithm",
            name="total_penalty_divisor",
            field=models.CharField(
                choices=[("WORDS", "All Words"), ("LEXEMES", "Unique Words (Lexemes)")],
                default="WORDS",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
