# Generated by Django 4.1.4 on 2024-01-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "app",
            "0006_rename_penalize_by_stem_algorithm_penalize_by_verb_stem_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="algorithm",
            name="phrases",
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name="algorithm",
            name="total_penalty_divisor",
            field=models.CharField(
                choices=[("WORDS", "All Words"), ("LEXEMES", "Unique Words (Lexemes)")],
                default="WORDS",
                max_length=50,
            ),
        ),
    ]
